version: '3.7'
services:
  twitter-to-kafka-service:
#    image: ${GROUP_ID}/twitter-to-kafka-service:${SERVICE_VERSION:-latest}
    image: 1e4e6307931c
    ports:
      - "5005:5005"
    volumes:
      - "./docker-logs:/workspace/twitter-to-kafka-service/logs"
      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
    user: root
    entrypoint: ["bash", "check-config-server-started.sh"]
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_EVENT-DRIVEN-MICROSERVICE-SPRING-BOOT-KAFKA-ES=info"
      - "LOGGING_LEVEL_ROOT=info"
      - "KAFKA-CONFIG_TOPIC-NAME=twitter-topic"
      - "KAFKA-CONFIG_BOOTSTRAP-SERVERS=kafka-broker-1:9092, kafka-broker-2:9092, kafka-broker-3:9092"
      - "KAFKA-CONFIG_SCHEMA-REGISTRY-URL=http://schema-registry:8081"
      - "TWITTER-TO-KAFKA-SERVICE_ENABLE-MOCK-TWEETS=true"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888"
    networks:
      - ${GLOBAL_NETWORK:-services}

  config-server:
#    image: ${GROUP_ID}/config-server:${SERVICE_VERSION:-latest}
    image: f94a6ce2831c
    ports:
      - "5006:5006"
    volumes:
      - "./docker-logs:/workspace/config-server/logs"
    user: root
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006 -Xms128m -Xmx256m"
      # for JCE
      - "ENCRYPT_KEY=${ENCRYPT_KEY}"
    networks:
      - ${GLOBAL_NETWORK:-services}