version: '3.7'
services:
  #  twitter-to-kafka-service:
  ##    image: ${GROUP_ID}/twitter-to-kafka-service:${SERVICE_VERSION:-latest}
  #    image: ${GROUP_ID}/twitter-to-kafka-service:0.0.1-SNAPSHOT
  ## image: 14e982af0035
  #    ports:
  #      - "5005:5005"
  #  depends_on: # depends on just specify the order, it doesn't do the healthcheck
  #    - config-server
  #    - kafka-broker-1
  #    - kafka-broker-2
  #    - kafka-broker-3
  #    volumes:
  #      - "./docker-logs:/workspace/twitter-to-kafka-service/logs"
  #      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
  #    user: root
  #    entrypoint: ["bash", "check-config-server-started.sh"]
  #    environment:
  #      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m"
  #      - "LOGGING_LEVEL_EVENT-DRIVEN-MICROSERVICE-SPRING-BOOT-KAFKA-ES=info"
  #      - "LOGGING_LEVEL_ROOT=info"
  #      - "KAFKA-CONFIG_TOPIC-NAME=twitter-topic"
  #      - "KAFKA-CONFIG_BOOTSTRAP-SERVERS=kafka-broker-1:9092, kafka-broker-2:9092, kafka-broker-3:9092"
  #      - "KAFKA-CONFIG_SCHEMA-REGISTRY-URL=http://schema-registry:8081"
  #      - "TWITTER-TO-KAFKA-SERVICE_ENABLE-MOCK-TWEETS=true"
  #      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888"
  #        - "ENCRYPT_KEY=${ENCRYPT_KEY}"

  #    networks:
  #      - ${GLOBAL_NETWORK:-services}

  kafka-to-elasticsearch-service:
    image: ${GROUP_ID}/kafka-to-elasticsearch-service:0.0.1-SNAPSHOT
    ports:
      - "5006:5006"
    volumes:
      - "./docker-logs:/workspace/kafka-to-elasticsearch-service/logs"
      - "./check-kafka-topics-created.sh:/usr/local/bin/check-kafka-topics-created.sh"
    user: root
    # or make it executable
    entrypoint: [ "bash", "check-kafka-topics-created.sh" ]
    depends_on: # depends on just specify the order, it doesn't do the healthcheck
      - config-server
      #      - twitter-to-kafka-service
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
      - elasticsearch-1
      - elasticsearch-2
      - elasticsearch-3
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_com_NP=info"
      - "LOGGING_LEVEL_ROOT=info"
      - "KAFKA-CONFIG_TOPIC-NAME=twitter-topic"
      - "KAFKA-CONFIG_BOOTSTRAP-SERVERS=kafka-broker-1:9092, kafka-broker-2:9092, kafka-broker-3:9092"
      - "KAFKA-CONFIG_SCHEMA-REGISTRY-URL=http://schema-registry:8081"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888"
      - "ELASTIC-CONFIG_INDEX-NAME=twitter-index"
      - "ELASTIC-CONFIG_CONNECTION-URL=http://elasticsearch-1:9200"
      - "ENCRYPT_KEY=${ENCRYPT_KEY}"
    networks:
      - ${GLOBAL_NETWORK:-services}

  config-server:
    #image: ${GROUP_ID}/config-server:${SERVICE_VERSION:-latest}
    image: ${GROUP_ID}/config-server:0.0.1-SNAPSHOT
    #    image: 5566c97316e0
    ports:
      #      - "5006:5006"
      - "8888:8888"
    volumes:
      - "./docker-logs:/workspace/config-server/logs"
    user: root
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006 -Xms128m -Xmx256m"
      # for JCE
      - "ENCRYPT_KEY=${ENCRYPT_KEY}"
    networks:
      - ${GLOBAL_NETWORK:-services}

  elasticsearch-query-service-1:
    image: ${GROUP_ID}/config-server:0.0.1-SNAPSHOT
    ports:
      - "5008:5008"
      - "8183:8183"
    volumes:
      - "./docker-logs:/workspace/elasticsearch-query-service/logs"
      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
    user: root
    entrypoint: [ "bash", "check-config-server-started.sh" ]
    depends_on:
      - config-server
      - elasticsearch-1
      - elasticsearch-2
      - elasticsearch-3
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_com_NP=info"
      - "LOGGING_LEVEL_ROOT=info"
      - "SERVER_PORT=8183"
      - "SERVER_SERVLET_CONTEXT-PATH=/elasticsearch-query-service"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888"
      - "ELASTIC-CONFIG_INDEX-NAME=twitter-index"
      - "ELASTIC-CONFIG_CONNECTION-URL=http://elasticsearch-1:9200"
      - "ENCRYPT_KEY=${ENCRYPT_KEY}"

    networks:
      - ${GLOBAL_NETWORK:-services}

  elasticsearch-query-service-2:
    image: ${GROUP_ID}/config-server:0.0.1-SNAPSHOT
    ports:
      - "5008:5008"
      - "8183:8185"
    volumes:
      - "./docker-logs:/workspace/elasticsearch-query-service/logs"
      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
    user: root
    entrypoint: [ "bash", "check-config-server-started.sh" ]
    depends_on:
      - config-server
      - elasticsearch-1
      - elasticsearch-2
      - elasticsearch-3
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_com_NP=info"
      - "LOGGING_LEVEL_ROOT=info"
      - "SERVER_PORT=8185"
      - "SERVER_SERVLET_CONTEXT-PATH=/elasticsearch-query-service"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888"
      - "ELASTIC-CONFIG_INDEX-NAME=twitter-index"
      - "ELASTIC-CONFIG_CONNECTION-URL=http://elasticsearch-1:9200"
      - "ENCRYPT_KEY=${ENCRYPT_KEY}"

    networks:
      - ${GLOBAL_NETWORK:-services}

  elasticsearch-query-web-client:
    image: ${GROUP_ID}/elasticsearch.query.webclient:${SERVICE_VERSION:-latest}
    ports:
      - "5010:5010"
      - "8184:8184"
    volumes:
      - "./docker-logs:/workspace/elasticsearch-query-web-client/logs"
      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
    user: root
    entrypoint: [ "check-config-server-started.sh" ]
    depends_on:
      - config-server
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5010 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_COM_MICROSERVICES_DEMO=info"
      - "LOGGING_LEVEL_ROOT=info"
      - "SERVER_PORT=8184"
      - "SERVER_SERVLET_CONTEXT-PATH=/elasticsearch-query-web-client"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888"
      - "ELASTICSEARCH-QUERY-WEB-CLIENT_WEB-CLIENT_BASE-URL=http://elasticsearch-query-service/elasticsearch-query-service/documents"
      - "ELASTICSEARCH-QUERY-WEB-CLIENT_WEB-CLIENT_INSTANCES_0_ID=elasticsearch-query-service-1"
      - "ELASTICSEARCH-QUERY-WEB-CLIENT_WEB-CLIENT_INSTANCES_0_HOST=elasticsearch-query-service-1"
      - "ELASTICSEARCH-QUERY-WEB-CLIENT_WEB-CLIENT_INSTANCES_0_PORT=8183"
      - "ELASTICSEARCH-QUERY-WEB-CLIENT_WEB-CLIENT_INSTANCES_1_ID=elasticsearch-query-service-2"
      - "ELASTICSEARCH-QUERY-WEB-CLIENT_WEB-CLIENT_INSTANCES_1_HOST=elasticsearch-query-service-2"
      - "ELASTICSEARCH-QUERY-WEB-CLIENT_WEB-CLIENT_INSTANCES_1_PORT=8185"
      - "ENCRYPT_KEY=${ENCRYPT_KEY}"
    networks:
      - ${GLOBAL_NETWORK:-services}